#[derive(Copy, Clone, Debug)]
pub enum KeyCode {
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LMenu,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RMenu,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,

    Other
}

impl KeyCode {
    pub fn from_glutin_code(code: ::glutin::VirtualKeyCode) -> KeyCode {
        match code {
            ::glutin::VirtualKeyCode::Key1 => KeyCode::Key1,
            ::glutin::VirtualKeyCode::Key2 => KeyCode::Key2,
            ::glutin::VirtualKeyCode::Key3 => KeyCode::Key3,
            ::glutin::VirtualKeyCode::Key4 => KeyCode::Key4,
            ::glutin::VirtualKeyCode::Key5 => KeyCode::Key5,
            ::glutin::VirtualKeyCode::Key6 => KeyCode::Key6,
            ::glutin::VirtualKeyCode::Key7 => KeyCode::Key7,
            ::glutin::VirtualKeyCode::Key8 => KeyCode::Key8,
            ::glutin::VirtualKeyCode::Key9 => KeyCode::Key9,
            ::glutin::VirtualKeyCode::Key0 => KeyCode::Key0,
            ::glutin::VirtualKeyCode::A => KeyCode::A,
            ::glutin::VirtualKeyCode::B => KeyCode::B,
            ::glutin::VirtualKeyCode::C => KeyCode::C,
            ::glutin::VirtualKeyCode::D => KeyCode::D,
            ::glutin::VirtualKeyCode::E => KeyCode::E,
            ::glutin::VirtualKeyCode::F => KeyCode::F,
            ::glutin::VirtualKeyCode::G => KeyCode::G,
            ::glutin::VirtualKeyCode::H => KeyCode::H,
            ::glutin::VirtualKeyCode::I => KeyCode::I,
            ::glutin::VirtualKeyCode::J => KeyCode::J,
            ::glutin::VirtualKeyCode::K => KeyCode::K,
            ::glutin::VirtualKeyCode::L => KeyCode::L,
            ::glutin::VirtualKeyCode::M => KeyCode::M,
            ::glutin::VirtualKeyCode::N => KeyCode::N,
            ::glutin::VirtualKeyCode::O => KeyCode::O,
            ::glutin::VirtualKeyCode::P => KeyCode::P,
            ::glutin::VirtualKeyCode::Q => KeyCode::Q,
            ::glutin::VirtualKeyCode::R => KeyCode::R,
            ::glutin::VirtualKeyCode::S => KeyCode::S,
            ::glutin::VirtualKeyCode::T => KeyCode::T,
            ::glutin::VirtualKeyCode::U => KeyCode::U,
            ::glutin::VirtualKeyCode::V => KeyCode::V,
            ::glutin::VirtualKeyCode::W => KeyCode::W,
            ::glutin::VirtualKeyCode::X => KeyCode::X,
            ::glutin::VirtualKeyCode::Y => KeyCode::Y,
            ::glutin::VirtualKeyCode::Z => KeyCode::Z,
            ::glutin::VirtualKeyCode::Escape => KeyCode::Escape,
            ::glutin::VirtualKeyCode::F1 => KeyCode::F1,
            ::glutin::VirtualKeyCode::F2 => KeyCode::F2,
            ::glutin::VirtualKeyCode::F3 => KeyCode::F3,
            ::glutin::VirtualKeyCode::F4 => KeyCode::F4,
            ::glutin::VirtualKeyCode::F5 => KeyCode::F5,
            ::glutin::VirtualKeyCode::F6 => KeyCode::F6,
            ::glutin::VirtualKeyCode::F7 => KeyCode::F7,
            ::glutin::VirtualKeyCode::F8 => KeyCode::F8,
            ::glutin::VirtualKeyCode::F9 => KeyCode::F9,
            ::glutin::VirtualKeyCode::F10 => KeyCode::F10,
            ::glutin::VirtualKeyCode::F11 => KeyCode::F11,
            ::glutin::VirtualKeyCode::F12 => KeyCode::F12,
            ::glutin::VirtualKeyCode::F13 => KeyCode::F13,
            ::glutin::VirtualKeyCode::F14 => KeyCode::F14,
            ::glutin::VirtualKeyCode::F15 => KeyCode::F15,
            ::glutin::VirtualKeyCode::Snapshot => KeyCode::Snapshot,
            ::glutin::VirtualKeyCode::Scroll => KeyCode::Scroll,
            ::glutin::VirtualKeyCode::Pause => KeyCode::Pause,
            ::glutin::VirtualKeyCode::Insert => KeyCode::Insert,
            ::glutin::VirtualKeyCode::Home => KeyCode::Home,
            ::glutin::VirtualKeyCode::Delete => KeyCode::Delete,
            ::glutin::VirtualKeyCode::End => KeyCode::End,
            ::glutin::VirtualKeyCode::PageDown => KeyCode::PageDown,
            ::glutin::VirtualKeyCode::PageUp => KeyCode::PageUp,
            ::glutin::VirtualKeyCode::Left => KeyCode::Left,
            ::glutin::VirtualKeyCode::Up => KeyCode::Up,
            ::glutin::VirtualKeyCode::Right => KeyCode::Right,
            ::glutin::VirtualKeyCode::Down => KeyCode::Down,
            ::glutin::VirtualKeyCode::Back => KeyCode::Back,
            ::glutin::VirtualKeyCode::Return => KeyCode::Return,
            ::glutin::VirtualKeyCode::Space => KeyCode::Space,
            ::glutin::VirtualKeyCode::Numlock => KeyCode::Numlock,
            ::glutin::VirtualKeyCode::Numpad0 => KeyCode::Numpad0,
            ::glutin::VirtualKeyCode::Numpad1 => KeyCode::Numpad1,
            ::glutin::VirtualKeyCode::Numpad2 => KeyCode::Numpad2,
            ::glutin::VirtualKeyCode::Numpad3 => KeyCode::Numpad3,
            ::glutin::VirtualKeyCode::Numpad4 => KeyCode::Numpad4,
            ::glutin::VirtualKeyCode::Numpad5 => KeyCode::Numpad5,
            ::glutin::VirtualKeyCode::Numpad6 => KeyCode::Numpad6,
            ::glutin::VirtualKeyCode::Numpad7 => KeyCode::Numpad7,
            ::glutin::VirtualKeyCode::Numpad8 => KeyCode::Numpad8,
            ::glutin::VirtualKeyCode::Numpad9 => KeyCode::Numpad9,
            ::glutin::VirtualKeyCode::AbntC1 => KeyCode::AbntC1,
            ::glutin::VirtualKeyCode::AbntC2 => KeyCode::AbntC2,
            ::glutin::VirtualKeyCode::Add => KeyCode::Add,
            ::glutin::VirtualKeyCode::Apostrophe => KeyCode::Apostrophe,
            ::glutin::VirtualKeyCode::Apps => KeyCode::Apps,
            ::glutin::VirtualKeyCode::At => KeyCode::At,
            ::glutin::VirtualKeyCode::Ax => KeyCode::Ax,
            ::glutin::VirtualKeyCode::Backslash => KeyCode::Backslash,
            ::glutin::VirtualKeyCode::Calculator => KeyCode::Calculator,
            ::glutin::VirtualKeyCode::Capital => KeyCode::Capital,
            ::glutin::VirtualKeyCode::Colon => KeyCode::Colon,
            ::glutin::VirtualKeyCode::Comma => KeyCode::Comma,
            ::glutin::VirtualKeyCode::Convert => KeyCode::Convert,
            ::glutin::VirtualKeyCode::Decimal => KeyCode::Decimal,
            ::glutin::VirtualKeyCode::Divide => KeyCode::Divide,
            ::glutin::VirtualKeyCode::Equals => KeyCode::Equals,
            ::glutin::VirtualKeyCode::Grave => KeyCode::Grave,
            ::glutin::VirtualKeyCode::Kana => KeyCode::Kana,
            ::glutin::VirtualKeyCode::Kanji => KeyCode::Kanji,
            ::glutin::VirtualKeyCode::LAlt => KeyCode::LAlt,
            ::glutin::VirtualKeyCode::LBracket => KeyCode::LBracket,
            ::glutin::VirtualKeyCode::LControl => KeyCode::LControl,
            ::glutin::VirtualKeyCode::LMenu => KeyCode::LMenu,
            ::glutin::VirtualKeyCode::LShift => KeyCode::LShift,
            ::glutin::VirtualKeyCode::LWin => KeyCode::LWin,
            ::glutin::VirtualKeyCode::Mail => KeyCode::Mail,
            ::glutin::VirtualKeyCode::MediaSelect => KeyCode::MediaSelect,
            ::glutin::VirtualKeyCode::MediaStop => KeyCode::MediaStop,
            ::glutin::VirtualKeyCode::Minus => KeyCode::Minus,
            ::glutin::VirtualKeyCode::Multiply => KeyCode::Multiply,
            ::glutin::VirtualKeyCode::Mute => KeyCode::Mute,
            ::glutin::VirtualKeyCode::MyComputer => KeyCode::MyComputer,
            ::glutin::VirtualKeyCode::NextTrack => KeyCode::NextTrack,
            ::glutin::VirtualKeyCode::NoConvert => KeyCode::NoConvert,
            ::glutin::VirtualKeyCode::NumpadComma => KeyCode::NumpadComma,
            ::glutin::VirtualKeyCode::NumpadEnter => KeyCode::NumpadEnter,
            ::glutin::VirtualKeyCode::NumpadEquals => KeyCode::NumpadEquals,
            ::glutin::VirtualKeyCode::OEM102 => KeyCode::OEM102,
            ::glutin::VirtualKeyCode::Period => KeyCode::Period,
            ::glutin::VirtualKeyCode::PlayPause => KeyCode::PlayPause,
            ::glutin::VirtualKeyCode::Power => KeyCode::Power,
            ::glutin::VirtualKeyCode::PrevTrack => KeyCode::PrevTrack,
            ::glutin::VirtualKeyCode::RAlt => KeyCode::RAlt,
            ::glutin::VirtualKeyCode::RBracket => KeyCode::RBracket,
            ::glutin::VirtualKeyCode::RControl => KeyCode::RControl,
            ::glutin::VirtualKeyCode::RMenu => KeyCode::RMenu,
            ::glutin::VirtualKeyCode::RShift => KeyCode::RShift,
            ::glutin::VirtualKeyCode::RWin => KeyCode::RWin,
            ::glutin::VirtualKeyCode::Semicolon => KeyCode::Semicolon,
            ::glutin::VirtualKeyCode::Slash => KeyCode::Slash,
            ::glutin::VirtualKeyCode::Sleep => KeyCode::Sleep,
            ::glutin::VirtualKeyCode::Stop => KeyCode::Stop,
            ::glutin::VirtualKeyCode::Subtract => KeyCode::Subtract,
            ::glutin::VirtualKeyCode::Sysrq => KeyCode::Sysrq,
            ::glutin::VirtualKeyCode::Tab => KeyCode::Tab,
            ::glutin::VirtualKeyCode::Underline => KeyCode::Underline,
            ::glutin::VirtualKeyCode::Unlabeled => KeyCode::Unlabeled,
            ::glutin::VirtualKeyCode::VolumeDown => KeyCode::VolumeDown,
            ::glutin::VirtualKeyCode::VolumeUp => KeyCode::VolumeUp,
            ::glutin::VirtualKeyCode::Wake => KeyCode::Wake,
            ::glutin::VirtualKeyCode::WebBack => KeyCode::WebBack,
            ::glutin::VirtualKeyCode::WebFavorites => KeyCode::WebFavorites,
            ::glutin::VirtualKeyCode::WebForward => KeyCode::WebForward,
            ::glutin::VirtualKeyCode::WebHome => KeyCode::WebHome,
            ::glutin::VirtualKeyCode::WebRefresh => KeyCode::WebRefresh,
            ::glutin::VirtualKeyCode::WebSearch => KeyCode::WebSearch,
            ::glutin::VirtualKeyCode::WebStop => KeyCode::WebStop,
            ::glutin::VirtualKeyCode::Yen => KeyCode::Yen
        }
    }
}
